### ISSUE TITLE
run.ps1

### ISSUE THREAD

**Issue by alfamuppet** [poofik/Huebner-Inverter#1]
I down loaded the master zip of the Huebner Inverter - Console Management to a file in desktop, when I tried to run.ps1 right click under powershell, this opened then closed and nothing else. Another version using the batch file (https://github.com/poofik/Huebner-Inverter) run as administrator also failed to work. any chance of an exe as windows is peculiar or is it better to install ubuntu

Regards

Dom H (UK)

**Comment by dimecho** [comment]
Thais is strange, normally Windows 7 and up comes pre-installed with PowerShell. But you can install it yourself (latest & greatest) version 5.0 https://www.microsoft.com/en-us/download/details.aspx?id=50395

Having exe opener will not help because the main script needs powershell.

**Comment by alfamuppet** [comment]
Hi

I installed powershell from your link as I had the folders but they were empty (8,1 x64). I ran the batch file and run.ps1 but
although they ran slower still nothing happened I assume that firefox was to start although it was already open then a new tab would appear?

regards

Dom Hannah
--------------------------------------------
On Fri, 6/1/17, poofik <notifications@github.com> wrote:

 Subject: Re: [poofik/Huebner-Inverter] run.ps1 (#1)
 To: "poofik/Huebner-Inverter" <Huebner-Inverter@noreply.github.com>
 Cc: "alfamuppet" <dominic.hannah@ymail.com>, "Author" <author@noreply.github.com>
 Date: Friday, 6 January, 2017, 20:08
 
 Thais is strange, normally
 Windows 7 and up comes pre-installed with PowerShell. But
 you can install it yourself (latest & greatest) version
 5.0 https://www.microsoft.com/en-us/download/details.aspx?id=50395
 Having exe opener will not help because the main script
 needs powershell.
 
 —
 You are receiving this because you authored the thread.
 Reply to this email directly, view
 it on GitHub, or mute
 the thread.

**Comment by alfamuppet** [comment]
Hi again

I got it working by commenting out the start of the script asking for administrator privilege (although I log on as administrator), then
installing PHP 5.6 manually because that part of the script went into a loop because it could not get online and then finally it tried every 
usb driver then gave up (did not have RS232 to USB converter). The firefox tab opened up but I had to "try again" twice to get a connection.
Powershell really complained about Elevate i.e. not such command etc etc. Windows is a pain with all the different version builds, mine is somewhere
between 8.0 and 8.1 and is a Spanish version (long story).

But got there in the end. Thanks

Regards

Dom Hannah
--------------------------------------------
On Fri, 6/1/17, poofik <notifications@github.com> wrote:

 Subject: Re: [poofik/Huebner-Inverter] run.ps1 (#1)
 To: "poofik/Huebner-Inverter" <Huebner-Inverter@noreply.github.com>
 Cc: "alfamuppet" <dominic.hannah@ymail.com>, "Author" <author@noreply.github.com>
 Date: Friday, 6 January, 2017, 20:08
 
 Thais is strange, normally
 Windows 7 and up comes pre-installed with PowerShell. But
 you can install it yourself (latest & greatest) version
 5.0 https://www.microsoft.com/en-us/download/details.aspx?id=50395
 Having exe opener will not help because the main script
 needs powershell.
 
 —
 You are receiving this because you authored the thread.
 Reply to this email directly, view
 it on GitHub, or mute
 the thread.
