### ISSUE TITLE
COM ports above 10 in Windows

### ISSUE THREAD

**Issue by nailgg** [poofik/Huebner-Inverter#2]
Hello,

I wasn't able to get PHP to connect to the inverter, then I found out that "fopen" cannot be used on COM10 and above ports in Windows. (Source: http://radiovibrations.com/php/com-port-access.php). I had to change the port number in devmgmt.msc, then I could successfully connect afterwards. Adding a notification to the COM port selection box would really be beneficial for other people using the interface.

Thanks,
Nail

**Comment by dimecho** [comment]
5d0e407 Fixes #2
